### ISSUE TITLE
Add support for MariaBackup

### ISSUE THREAD

**Issue by ManjotS** [twindb/backup#148]
### Description

Please  add support for MariaBackup (drop in replacement for  xtrabackup)  to support MariaDB 10.2+

**Comment by ernstae** [comment]
I'm using a workaround for MySQL 8.0 environments by specifying the `--xtrabackup-binary=/usr/bin/xtrabackup` as an argument.

Can you do the same thing with your MariaBackup binary?

**Comment by ManjotS** [comment]
this seems viable, thanks!

**Comment by akuzminsky** [comment]
There were a few obstacles along the way.

1. _Binaries_. MariaBackup ships binaries `mariabackup` and `mbstream`. I many places `xtrabackup`/`xbstream` were hardcoded, so that needed to be fixed.
2. Different log format in Xtrabackup and Mariabackup. Unfortunately there is no better way to find the last LSN for the incremental backups than parse the stderr log. Formally, the LSN is stored in `xtrabackup_checkpoints` (or similar name, don't remember exactly). If you stream a backup copy externally, you'd need to download, uncompress, decrypt - ugh. So, parsing stderr - mariabackup and xtrabackup have different formats.
3. Mariabackup and XtraBackup _behave differently with default CLI options_. Particularly, default username, my.cnf. etc.
